# Generated by Django 4.0.4 on 2022-05-18 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='preamble',
            new_name='intro',
        ),
    ]
