# Generated by Django 4.0.4 on 2022-05-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_preamble_news_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='intro',
            new_name='preamble',
        ),
    ]
