# Generated by Django 4.0.4 on 2022-05-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_intro_news_preamble'),
    ]

    operations = [
    ]
