# Generated by Django 4.0.4 on 2022-05-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_data_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='description_as_makrdown',
            new_name='description_as_markdown',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='description_as_makrdown',
            new_name='description_as_markdown',
        ),
    ]
